--Create a Database Customer_Shopping in sql 
create database Customer_shopping
--Check once python Clean and updated dataframe upload in database 
select* from customer
--Q1. What is the total revenue generated by Male vs Female?
select gender,sum([purchase_amount_(usd)]) as total_revenue
from customer
group by gender
--Q2.Find which product categories contribute the most to total sales.
select
    category,
    sum([purchase_amount_(usd)]) AS total_revenue,
    count(*) AS total_orders
from customer
group by category
order by total_revenue desc
--Q3.which are the top 5 products with the highest average  review rating?
select top 5 (item_purchased) as product ,round(avg(review_rating),2) as Average_Review_Rating
from customer
group by item_purchased
order  by avg(review_rating) desc

--Q4.Do subsribed customers spend more? compare average spend and total revenue between 
--subscribers and non- subscribers.
select subscription_status ,count(customer_id) as total_customers,
round(avg([purchase_amount_(usd)]),2) as average_spend,
round(sum([purchase_amount_(usd)]),2) as  total_revenue 
from customer
group by subscription_status
--Q5. comapre the average purchase amounts between standard and express shipping 
select shipping_type,avg([purchase_amount_(usd)]) as avg_amount
from customer
where shipping_type in('Standard','Express')
group by shipping_type

--Q6 Which 5 products have the highest percentage of purchase with discounts applied?
select top 5 (item_purchased) as products,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate 
from Customer
group by item_purchased
order by discount_rate desc
--Q7.what are the top 3 purchase products within each catogery?
with  item_counts as (
select  category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rnk
from Customer
group by category,item_purchased)
select item_rnk,category,item_purchased,total_orders
from item_counts
where item_rnk<=3
--Q8. segment cusomers into new ,returning,and loyal based on their total 
--numberof previous purchase ,and show the count of each segment?
with customer_type as(
select customer_id,previous_purchases,
case
   when previous_purchases=1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else'loyal'
   end as customer_segments
from Customer
)
select customer_segments,count(*) as total_cutomers from customer_type
group by customer_segments
--Q9.what is the revenue contribution of each  age group  ?
select age_group,sum([purchase_amount_(usd)]) as revenue
from Customer
group by age_group
order by revenue desc

--Q10.Seasonal Trends: Analyzed sales distribution across different seasons.
select season,
count(*) as total_orders,
sum([purchase_amount_(usd)]) as  total_revenue,
round(avg([purchase_amount_(usd)]),2) as  avg_purchase_value
from Customer
group by season
order by total_revenue desc